name: Docker Build and Push

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - '.github/workflows/docker-build.yml'

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: cloud-operations-portal

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::586789648037:role/cloud-operations-portal-github-actions-terraform-role
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t $ECR_REPOSITORY:latest ./app

      - name: Tag Docker image
        run: |
          docker tag $ECR_REPOSITORY:latest 586789648037.dkr.ecr.us-east-1.amazonaws.com/$ECR_REPOSITORY:latest

      - name: Push Docker image
        run: |
          docker push 586789648037.dkr.ecr.us-east-1.amazonaws.com/$ECR_REPOSITORY:latest
